[default.extend-words]

[files]
extend-exclude = [
  # error: `manualy` should be `manually`
  "src/data/blog/2025-06-13-diary.md",
  # error: `Fre` should be `Free`
  "src/data/blog/2025-08-02-diary.md",
]
